# Generated by Django 4.2 on 2023-05-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_profile_zodiac_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='children',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dealbreaker',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='drink',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Occasionally', 'Occasionally')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fun_date_idea',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Not Disclosed', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(default='Not Disclosed', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Open Relationship', 'Open Relationship')], default='Single'),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoke',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Occasionally', 'Occasionally')], null=True),
        ),
        migrations.AlterField(
            model_name='dateideas',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height_feet',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='5'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height_inches',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default='0'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zodiac_sign',
            field=models.CharField(blank=True, choices=[('Aries', 'Aries'), ('Taurus', 'Taurus'), ('Gemini', 'Gemini'), ('Cancer', 'Cancer'), ('Leo', 'Leo'), ('Virgo', 'Virgo'), ('Libra', 'Libra'), ('Scorpio', 'Scorpio'), ('Sagittarius', 'Sagittarius'), ('Capricorn', 'Capricorn'), ('Aquarius', 'Aquarius'), ('Pisces', 'Pisces')], null=True),
        ),
    ]
