# Generated by Django 4.2 on 2023-05-10 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_dateideas_time_alter_dateideas_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateideas',
            name='time',
        ),
    ]
