# Generated by Django 4.2 on 2023-05-12 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_potentialmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialmatch',
            name='potential_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='potential_matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
